apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-v8dn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-v8dn
    app.kubernetes.io/part-of: tkrw-pr712-0075-0023-app
  name: devfile-sample-v8dn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-v8dn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-v8dn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0023-tenant/tkrw-pr712-0075-0023-app/devfile-sample-v8dn@sha256:4c4b7f7076464e7e814ed4a4acdb6189d7b8c5c145875f6f0ba2c093a10ae140
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
